### ISSUE TITLE
could not find CMAKE_PROJECT_NAME in Cache

### ISSUE THREAD

**Issue by nazububu** [donn/nudelta#36]
Hey hey.
Thank you for your tool, I hope it good :)

I trying to execute yarn build, and got error: 
```could not find CMAKE_PROJECT_NAME in Cache```

Can you please tell me what I am doing wrong?

**Keyboard**: Nuphy Air75
**NuDelta Version**: 0.6.6
**Distro**: Ubuntu 20.04

Thank you

```
info TOOL Using Unix Makefiles generator.
info CMD BUILD
info RUN [
info RUN   'cmake',
info RUN   '--build',
info RUN   '/home/nazar/nudelta/build',
info RUN   '--config',
info RUN   'Release'
info RUN ]
Error: could not find CMAKE_PROJECT_NAME in Cache
ERR! OMG Error: Process terminated: 1
ERR! OMG     at ChildProcess.<anonymous> (/home/nazar/nudelta/node_modules/cmake-js/lib/processHelpers.js:32:32)
ERR! OMG     at ChildProcess.emit (node:events:513:28)
ERR! OMG     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
Error: Cmake-js exited with a non-zero code
    at main (file:///home/nazar/nudelta/util/build-native.js:24:15)
```

**Comment by nazububu** [comment]
Sorry, this problem resolved with packages installation and clear.
But another problem now.

```
verb CFG {"directory":"/home/nazar/nudelta","cmakePath":null,"runtime":"electron","runtimeVersion":"21.2.1","arch":"x64","cMakeOptions":{},"out":"/home/nazar/nudelta/build","isNodeApi":false}
info TOOL Using Unix Makefiles generator.
info CMD BUILD
info RUN [
info RUN   'cmake',
info RUN   '--build',
info RUN   '/home/nazar/nudelta/build',
info RUN   '--config',
info RUN   'Release'
info RUN ]
make: Makefile: No such file or directory
make: *** No rule to make target 'Makefile'.  Stop.
ERR! OMG Error: Process terminated: 2
ERR! OMG     at ChildProcess.<anonymous> (/home/nazar/nudelta/node_modules/cmake-js/lib/processHelpers.js:32:32)
ERR! OMG     at ChildProcess.emit (node:events:513:28)
ERR! OMG     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
Error: Cmake-js exited with a non-zero code
    at main (file:///home/nazar/nudelta/util/build-native.js:24:15)
```

I am doing something wrong? Just yarn build

**Comment by donn** [comment]
Hello Nazar- no, this is weird. I've never ecountered this.

Can you try the pre-built versions at https://github.com/donn/nudelta/releases/tag/latest ?

**Comment by donn** [comment]
Staled out.
